platform :ios, ‘8.0’

target ‘ColorGuideApp’ do

  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'GPUImage', '~> 0.1.7'
  pod 'Masonry', '~> 1.0.2'

end
